# Dockerfile
FROM public.ecr.aws/lambda/python:3.10

# Copy function code
COPY src/curatedzoneprocess.py ${LAMBDA_TASK_ROOT}
COPY requirements.curated.txt ${LAMBDA_TASK_ROOT}
RUN pip install --no-cache-dir -r requirements.curated.txt


# Set the CMD to your handler
CMD ["curatedzoneprocess.handler"]